name: "Test"

concurrency:
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - master
  push:
    branches:
    - br_demo
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kong plugin repo
      uses: actions/checkout@v6
      with:
        path: quiz-kong-plugin

    - name: Checkout kong pongo repo
      uses: actions/checkout@v6
      with:
        repository: jeanerpp/kong-pongo
        ref: br_demo
        path: kong-pongo

    - name: Setup kong pongo
      run: |
        mkdir -p ~/.local/bin
        ln -s $(realpath kong-pongo/pongo.sh) ~/.local/bin/pongo

    - name: Run tests with custom kong pongo
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        cd quiz-kong-plugin
        pongo run --coverage

    - name: Check coverage report
      run: |
        cd quiz-kong-plugin
        total_cov=$(grep -w '^Total' luacov.report.out | tail -1 | gawk '{print $NF;}')
        echo "Total coverage rate: $total_cov"
        
        # Remove % and compare numerically using bc
        cov_num=${total_cov%\%}
        if (( $(echo "$cov_num > 90.0" | bc -l) )); then
          echo "Coverage is greater than 90%"
        else
          echo "Coverage is less than or equal to 90%"
          exit 1
        fi
