name: "Test"

concurrency:
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - master
  push:
    branches:
    - br_demo
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kong plugin repo
      uses: actions/checkout@v6
      with:
        path: quiz-kong-plugin

    - name: Checkout kong pongo repo
      uses: actions/checkout@v6
      with:
        repository: jeanerpp/kong-pongo
        ref: br_demo
        path: kong-pongo

    - name: Setup kong pongo
      run: |
        mkdir -p ~/.local/bin
        ln -s $(realpath kong-pongo/pongo.sh) ~/.local/bin/pongo

    - name: Run tests with custom kong pongo
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        cd quiz-kong-plugin
        pongo run -- --Xoutput "--color" --coverage
